version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "thudsonbu"
  - package-ecosystem: "npm"
    directory: "/www"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "thudsonbu"
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "thudsonbu"
