name: Agenda PR Pretest

on: [push]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 6.0

      - run: npm run keygen

      - run: npm i

      - run: npm run lint

      - run: npm run coverage

      - run: npm run build
